quarkus:
  datasource:
    db-kind: postgresql
    jdbc:
      url: jdbc:postgresql://localhost:5432/chiroerp
    username: chiroerp
    password: chiroerp
  hibernate-orm:
    database:
      generation: validate
  kafka:
    bootstrap-servers: localhost:9092
